export const ITEMS = {
  pomegranate: ['Pomegranate', '🍎', 'A small red beginning.'],
  jam: ['Sunrise jam', '🫙', 'Summer, carefully bottled.'],
  bread: ['Warm sourdough', '🍞', 'Still warm under your flipper.'],
  spool: ['Copper thread', '🧵', 'Strong enough to mend a sail.'],
  lure: ['Silver lure', '🪝', 'An irresistible little shimmer.'],
  fish: ['Moonfish', '🐟', 'Catch these at the harbour.'],
  pearl: ['Sea pearl', '🦪', 'A tiny moon from the ocean.'],
  lens: ['Old spyglass', '🔭', 'The horizon feels closer.'],
  map: ['Tide chart', '🗺️', 'Every current has a story.'],
  seeds: ['Orchard seeds', '🌱', 'Tomorrow, in a paper packet.'],
  honey: ['Wildflower honey', '🍯', 'A thousand tiny flights.'],
  herbs: ['Wild thyme', '🌿', 'Growing in the orchard.'],
  tea: ['Keeper’s tea', '🍵', 'A recipe for listening.'],
  wool: ['Cloud wool', '🧶', 'Ridiculously soft.'],
  scarf: ['Woven shawl', '🧣', 'Made for a cold night.'],
  wood: ['Driftwood', '🪵', 'Gather along the southern shore.'],
  carving: ['Little wooden whale', '🐋', 'A whale that fits in a pocket.'],
  gear: ['Brass gear', '⚙️', 'One missing piece.'],
  oil: ['Lantern oil', '🏺', 'A bottled promise of light.'],
  lantern: ['Storm lantern', '🏮', 'Some things are worth carrying.'],
  crystal: ['Aurora crystal', '💎', 'It remembers the northern lights.'],
  bell: ['Keeper’s bell', '🔔', 'Three notes bring the light home.'],
  deed: ['Workshop deed', '📜', 'A very small piece of the island.'],
  tools: ['Master’s tools', '🛠️', 'Well used. Well loved.'],
  mushroom: ['Amber mushrooms', '🍄', 'Found beneath the eastern pines.'],
  feast: ['Festival hamper', '🧺', 'Enough good things to share.'],
  tapestry: ['Island tapestry', '🪡', 'Everyone has a thread.'],
  compass: ['Star compass', '🧭', 'It points toward belonging.'],
  ship: ['Model sailboat', '⛵', 'Built to dream in.'],
  key: ['Brass house key', '🗝️', 'There is a door waiting for this.'],
  home: ['A place to call home', '🏡', 'Yours. At last.'],
  shell: ['Sea glass', '🔹', 'The ocean makes beautiful mistakes.'],
  ribbon: ['Friendship ribbon', '🎀', 'A little kindness comes back around.'],
};
export const DISTRICTS = [
  {
    name: 'Littlewake Harbour',
    short: 'Harbour',
    x: -36,
    z: 61,
    color: '#71b3bb',
  },
  {
    name: 'Pebblebrook Village',
    short: 'Village',
    x: 0,
    z: 6,
    color: '#e6b976',
  },
  {
    name: 'Honeyhill Orchard',
    short: 'Orchard',
    x: -65,
    z: -14,
    color: '#aec982',
  },
  { name: 'Whispering Pines', short: 'Pines', x: 66, z: 12, color: '#71a59b' },
  { name: 'Aurora Rise', short: 'Rise', x: 24, z: -67, color: '#aebed8' },
  {
    name: 'Northlight Point',
    short: 'Lighthouse',
    x: -54,
    z: -70,
    color: '#eacb8d',
  },
];
export const NPCS = [
  {
    id: 'mara',
    name: 'Mara',
    role: 'The jam maker',
    x: -27,
    z: 48,
    color: 0xda8067,
    kind: 'penguin',
    line: 'Every great adventure starts with breakfast. That is a fact. Probably.',
    rumour:
      'Pip’s sourdough wants something sweet. He says bread is a very patient spoon.',
  },
  {
    id: 'pip',
    name: 'Pip',
    role: 'The baker',
    x: 5,
    z: 19,
    color: 0xe2b15a,
    kind: 'puffin',
    line: 'I measure happiness in crumbs. You look like you could use a few.',
    rumour: 'Iona at the harbour has been mending nets since sunrise.',
  },
  {
    id: 'iona',
    name: 'Iona',
    role: 'The sail mender',
    x: -48,
    z: 68,
    color: 0x779cc2,
    kind: 'penguin',
    line: 'The sea takes things apart. I put them back together. We have an understanding.',
    rumour: 'Finn makes fishing lures from the strangest things.',
  },
  {
    id: 'finn',
    name: 'Finn',
    role: 'The patient fisher',
    x: 1,
    z: 78,
    color: 0x6d9984,
    kind: 'otter',
    line: 'The trick is to think like a fish. Mostly I think about lunch.',
    rumour:
      'Moonfish like the silver fishing spots by the dock. Press when the float crosses the gold patch.',
  },
  {
    id: 'pearl',
    name: 'Pearl',
    role: 'The beachcomber',
    x: 45,
    z: 62,
    color: 0xd999aa,
    kind: 'penguin',
    line: 'The ocean never throws anything away. It just gives it a very long polish.',
    rumour: 'Captain Sol has a weakness for pearls. And dramatic pauses.',
  },
  {
    id: 'sol',
    name: 'Captain Sol',
    role: 'The retired explorer',
    x: -68,
    z: 47,
    color: 0xc3895b,
    kind: 'puffin',
    line: 'I have sailed every sea on the map. The kettle is my favourite destination.',
    rumour: 'Ada sees things in the stars that the rest of us miss.',
  },
  {
    id: 'ada',
    name: 'Ada',
    role: 'The stargazer',
    x: 32,
    z: -58,
    color: 0x9693b7,
    kind: 'penguin',
    line: 'The stars are old stories, travelling a very long way to be heard.',
    rumour: 'Bram needs a tide chart. Apparently bees get seasick.',
  },
  {
    id: 'bram',
    name: 'Bram',
    role: 'The orchard keeper',
    x: -70,
    z: 2,
    color: 0xad9d55,
    kind: 'otter',
    line: 'I plant trees for summers I have not met yet. It feels like a sensible investment.',
    rumour: 'Clover knows how to persuade seeds to wake up.',
  },
  {
    id: 'clover',
    name: 'Clover',
    role: 'The beekeeper',
    x: -54,
    z: -32,
    color: 0xe4b954,
    kind: 'penguin',
    line: 'The bees think I work for them. Please don’t tell them otherwise.',
    rumour:
      'Look for thyme between the orchard trees. Moss will brew something lovely.',
  },
  {
    id: 'moss',
    name: 'Moss',
    role: 'The tea tender',
    x: 58,
    z: 7,
    color: 0x89996d,
    kind: 'otter',
    line: 'Come in from the world a moment. Even adventures need to steep.',
    rumour: 'Nell at Aurora Rise gets chilly counting her clouds.',
  },
  {
    id: 'nell',
    name: 'Nell',
    role: 'The cloud shepherd',
    x: 5,
    z: -75,
    color: 0xbb9db8,
    kind: 'penguin',
    line: 'That cloud looks like a potato. A magnificent potato.',
    rumour: 'June can weave a whole sunset into a shawl.',
  },
  {
    id: 'june',
    name: 'June',
    role: 'The weaver',
    x: 23,
    z: -4,
    color: 0xbe7969,
    kind: 'penguin',
    line: 'One thread is fragile. Many threads can keep someone warm.',
    rumour:
      'Alder’s workshop is in the eastern pines. Bring him driftwood from the beach.',
  },
  {
    id: 'alder',
    name: 'Alder',
    role: 'The woodcarver',
    x: 72,
    z: 28,
    color: 0x9a7956,
    kind: 'otter',
    line: 'Wood remembers being a tree. I try to make things it would be happy to become.',
    rumour:
      'Tess loves little mechanical things. And whales. Especially whales.',
  },
  {
    id: 'tess',
    name: 'Tess',
    role: 'The tinkerer',
    x: -10,
    z: -10,
    color: 0x709bb0,
    kind: 'puffin',
    line: 'It is not broken. It is having a complicated afternoon.',
    rumour: 'Orin has been trying to repair the lighthouse for years.',
  },
  {
    id: 'orin',
    name: 'Orin',
    role: 'The lighthouse keeper',
    x: -49,
    z: -63,
    color: 0xd5ab65,
    kind: 'penguin',
    line: 'A lighthouse doesn’t tell ships where to go. Just that they aren’t alone.',
    rumour:
      'There are three wind chimes: orchard, pines, rise. Low, middle, high. The old song.',
  },
  {
    id: 'lumi',
    name: 'Lumi',
    role: 'The lantern maker',
    x: -35,
    z: 0,
    color: 0xca9473,
    kind: 'penguin',
    line: 'A little light can make a very large dark feel smaller.',
    rumour:
      'Eira searches the rise for crystals. A storm lantern would help her.',
  },
  {
    id: 'eira',
    name: 'Eira',
    role: 'The aurora watcher',
    x: 61,
    z: -51,
    color: 0x8baac3,
    kind: 'puffin',
    line: 'There are colours up there that haven’t learned their names yet.',
    rumour:
      'Orin’s old bell was cut from the same crystal as the lighthouse lens.',
  },
  {
    id: 'bea',
    name: 'Bea',
    role: 'The village cook',
    x: 35,
    z: 27,
    color: 0xdca567,
    kind: 'otter',
    line: 'A table is just a piece of wood until you put friends around it.',
    rumour: 'Amber mushrooms grow in the eastern forest. Three make a feast.',
  },
  {
    id: 'wren',
    name: 'Wren',
    role: 'The post keeper',
    x: -21,
    z: 22,
    color: 0x8cacba,
    kind: 'puffin',
    line: 'Most letters say the same thing, really. I thought of you.',
    rumour:
      'Someone left twelve little postcards around the island. The old keeper, I think.',
  },
  {
    id: 'hazel',
    name: 'Hazel',
    role: 'The house keeper',
    x: 57,
    z: -77,
    color: 0xc29c7b,
    kind: 'penguin',
    line: 'An empty house is only waiting for the right footsteps.',
    rumour:
      'That little cottage? The one with the blue roof? It has a very good morning view.',
  },
];
export const TRADES = [
  [
    'mara',
    ['pomegranate'],
    ['jam'],
    'A small red beginning',
    'A pomegranate! I haven’t seen one since I was a chick. Let me make you a deal: my best sunrise jam for that little treasure.',
    'You → “One day, I’m going to trade my way to a house.”\nMara → “Then I’d better make this a very good jar.”',
  ],
  [
    'pip',
    ['jam'],
    ['bread'],
    'A toast to possibilities',
    'Mara’s sunrise jam? That deserves the loaf I’ve been saving. Warm bread opens doors. Sometimes literally.',
    'Pip wraps the loaf twice. “For the journey. No one bargains well on an empty belly.”',
  ],
  [
    'iona',
    ['bread'],
    ['spool'],
    'A stitch in the tide',
    'Warm bread. Oh, you wonderful little bird. Take this copper thread. Finn has been asking for it.',
    '“A home, you say? Start by getting to know the shore.”',
  ],
  [
    'finn',
    ['spool'],
    ['lure'],
    'Something to fish for',
    'Copper thread! Perfect for my new lure. Here—keep the prototype. Try the fishing spot beside my dock.',
    '“Watch the float. When it reaches the gold patch, press E. No hurry. The fish have nowhere else to be.”',
  ],
  [
    'pearl',
    ['fish', 'fish'],
    ['pearl'],
    'Two fish, one little moon',
    'Bring me two moonfish and this pearl is yours. I am excellent at finding pearls. Terrible at finding dinner.',
    'Pearl holds it up to the sun. “A whole moon. Pocket sized.”',
  ],
  [
    'sol',
    ['pearl'],
    ['lens'],
    'A wider horizon',
    'I found this spyglass on my first voyage. I’d like my last treasure to be something the ocean made itself.',
    '“The world gets bigger when you look closely.”',
  ],
  [
    'ada',
    ['lens'],
    ['map'],
    'Written in the tides',
    'A spyglass! Now I can check whether that star really is winking. Take my tide chart; Bram needs one.',
    '“It is winking. I knew it.”',
  ],
  [
    'bram',
    ['map'],
    ['seeds'],
    'Good things take roots',
    'A tide chart will get my saplings safely across the bay. These rare seeds belong in Clover’s careful flippers.',
    '“You’re planting something too, little one. You just can’t see it yet.”',
  ],
  [
    'clover',
    ['seeds'],
    ['honey'],
    'A thousand tiny wings',
    'Those are moonblossom seeds! My bees will write songs about you. Quiet songs. Mostly buzzing.',
    '“Take this honey. Gather three sprigs of thyme here and Moss will make you a proper pot.”',
  ],
  [
    'moss',
    ['honey', 'herbs', 'herbs', 'herbs'],
    ['tea'],
    'A moment to steep',
    'Honey and wild thyme. A cup for you, and a flask for Nell. She forgets to come down from the clouds.',
    'You share a quiet cup. For the first time, the island feels less like a stop and more like a place.',
  ],
  [
    'nell',
    ['tea'],
    ['wool'],
    'Soft as the sky',
    'Keeper’s tea! My flippers are thawing just looking at it. Have some of my finest cloud wool.',
    '“That cloud looks like you. A very ambitious potato.”',
  ],
  [
    'june',
    ['wool'],
    ['scarf'],
    'A little warmth travels',
    'I can make a shawl from this. Take it to Alder; he keeps giving his blankets away to cold birds.',
    '“Find three pieces of driftwood along the southern shore, too. He’ll make you something special.”',
  ],
  [
    'alder',
    ['scarf', 'wood', 'wood', 'wood'],
    ['carving'],
    'What the sea leaves behind',
    'A shawl, and wood the sea has already shaped. Sit a moment. There is a whale hiding in here.',
    'Alder’s knife whispers. A little whale emerges. “Some things just need someone to see them.”',
  ],
  [
    'tess',
    ['carving'],
    ['gear'],
    'Small things fit together',
    'A WHALE. A tiny whale. This is an extremely serious engineering event. You can have my rare brass gear.',
    '“It fits Orin’s lighthouse mechanism. I’ve been too shy to bring it over.”',
  ],
  [
    'orin',
    ['gear'],
    ['oil'],
    'The keeper’s promise',
    'The missing gear. Tess remembered. With a storm lantern and a crystal bell, we could wake Northlight again.',
    '“Lumi can use this oil. You have a way of keeping things moving, don’t you?”',
  ],
  [
    'lumi',
    ['oil'],
    ['lantern'],
    'A light worth carrying',
    'This is the old keeper’s oil. I’ll make a lantern worthy of it. Eira will need it on the rise.',
    '“Bring a little light wherever you go. The rest usually follows.”',
  ],
  [
    'eira',
    ['lantern'],
    ['crystal'],
    'A colour without a name',
    'With this I can cross the ridge safely. Take the crystal I found last winter. It hums in my pocket.',
    '“Orin will know what to do with it. He always did.”',
  ],
  [
    'orin',
    ['crystal'],
    ['bell'],
    'The island’s old song',
    'The bell is yours. Wake the three wind chimes in order: Orchard, Pines, Rise. Then bring it back to me.',
    '“Low. Middle. High. A song that says: we are still here.”',
  ],
  [
    'orin',
    ['bell'],
    ['deed'],
    'Bring the light home',
    'You remembered the song. Listen—the whole island is answering. Take my old workshop deed. Build something good.',
    'The keeper looks at you for a long moment. “You came looking for a house. Look what you’ve already made.”',
  ],
  [
    'alder',
    ['deed'],
    ['tools'],
    'Room to make things',
    'A real workshop! No more carving in the rain. You should take my master’s tools. Bea has wanted a set for ages.',
    '“I’ll build a long table first. Long enough for everyone.”',
  ],
  [
    'bea',
    ['tools', 'mushroom', 'mushroom', 'mushroom'],
    ['feast'],
    'A table for everyone',
    'Good tools, three amber mushrooms… yes. We can make a festival out of this. Take this hamper to June.',
    '“Tell her to bring everyone. Yes, everyone. Especially the bees.”',
  ],
  [
    'june',
    ['feast'],
    ['tapestry'],
    'Every neighbour, a thread',
    'A feast for the whole village? Then this tapestry is yours. Every home here has a thread in it.',
    'You find a small red thread at the edge. “That one’s you,” June says.',
  ],
  [
    'ada',
    ['tapestry'],
    ['compass'],
    'A different kind of north',
    'The whole island, woven together. I’d trade my star compass for that. It has never led me anywhere uninteresting.',
    '“It doesn’t point north exactly. It points toward what matters. Very inconvenient for cartography.”',
  ],
  [
    'sol',
    ['compass'],
    ['ship'],
    'The last little voyage',
    'My old compass! Ada has kept it all these years. Take my model sailboat. Wren used to watch me build it.',
    '“Some voyages end right where they should have begun.”',
  ],
  [
    'wren',
    ['ship'],
    ['ribbon'],
    'Something that comes back',
    'He remembered. I was so little when he built this. Here—my friendship ribbon. Hazel knows what it means.',
    '“This ribbon has travelled through every home on the island. There’s one left.”',
  ],
  [
    'hazel',
    ['ribbon'],
    ['key'],
    'The right footsteps',
    'That ribbon. Then everyone agrees. The blue-roof cottage needs a keeper. I think it has found one.',
    '“Take the key to Orin. He’ll sign the house over properly. He insists on a little ceremony.”',
  ],
  [
    'orin',
    ['key'],
    ['home'],
    'A place to call home',
    'One pomegranate became a jar, a loaf, a light, a gathering. I think that is a very fair trade for a home.',
    '“The cottage is yours. Hazel is waiting at the door. Go on, little neighbour.”',
  ],
  [
    'hazel',
    ['home'],
    [],
    'Home, at last',
    'The kettle is on. The chair faces the sea. You can stop running now, NarNar. Welcome home.',
    'And for once, the little penguin had absolutely nowhere else to be.',
  ],
].map((t, i) => ({
  id: i,
  npc: t[0],
  needs: t[1],
  gives: t[2],
  title: t[3],
  dialogue: t[4],
  after: t[5],
  chime: i === 18,
}));
export const CHAPTERS = [
  { at: 0, title: 'A pocketful of possibility' },
  { at: 6, title: 'Putting down roots' },
  { at: 12, title: 'A light in the distance' },
  { at: 19, title: 'The things we make together' },
  { at: 25, title: 'The way home' },
];
export const NOTES = [
  [
    -58,
    77,
    'I used to think a home was a place that kept the weather out. — O.',
  ],
  [23, 68, 'Then someone left warm bread on my doorstep. — O.'],
  [
    -80,
    21,
    'And someone planted a tree where I could see it from my window. — O.',
  ],
  [-43, -21, 'The bees came. They did not ask permission. I liked that. — O.'],
  [-14, 38, 'A house has walls. A home has people who knock on them. — O.'],
  [
    42,
    4,
    'Tess fixed my clock. It still runs slow. We have more time for tea now. — O.',
  ],
  [83, 39, 'Alder made me a chair. He said it was for watching the sea. — O.'],
  [68, -23, 'I watched my neighbours instead. Far more interesting. — O.'],
  [
    16,
    -49,
    'Nell says every cloud is going somewhere. I am glad I am not a cloud. — O.',
  ],
  [
    -64,
    -54,
    'The light went out. For a while, I forgot it could come back. — O.',
  ],
  [41, -87, 'Someone new is coming. I can feel it in the tide. — O.'],
  [73, -65, 'If you have found these: welcome. I saved you the chair. — Orin.'],
].map((a, i) => ({ id: `note${i}`, x: a[0], z: a[1], text: a[2] }));
export const CHIMES = [
  { id: 'orchard', name: 'Orchard chime', x: -78, z: -30, note: 261.63 },
  { id: 'pines', name: 'Pines chime', x: 82, z: -10, note: 329.63 },
  { id: 'rise', name: 'Rise chime', x: 22, z: -87, note: 392 },
];
export const RESOURCES = [
  ...[
    [-44, 80],
    [-23, 86],
    [20, 83],
    [53, 70],
    [-67, 63],
  ].map((p, i) => ({ id: `wood${i}`, type: 'wood', x: p[0], z: p[1] })),
  ...[
    [-62, -20],
    [-80, -5],
    [-47, -40],
    [-67, -42],
    [-84, -20],
  ].map((p, i) => ({ id: `herbs${i}`, type: 'herbs', x: p[0], z: p[1] })),
  ...[
    [70, 42],
    [85, 17],
    [49, -8],
    [69, -20],
    [88, -2],
  ].map((p, i) => ({ id: `mushroom${i}`, type: 'mushroom', x: p[0], z: p[1] })),
  ...[
    [-35, 77],
    [34, 80],
    [65, 50],
    [-80, 42],
    [5, 88],
    [78, 57],
  ].map((p, i) => ({ id: `shell${i}`, type: 'shell', x: p[0], z: p[1] })),
];
export const FISH_SPOT = {
  id: 'fishing',
  name: 'Moonfish shallows',
  x: 9,
  z: 82,
};
export const CHAPTER = (n) => CHAPTERS.filter((c) => n >= c.at).at(-1);
export const nameOf = (id) => ITEMS[id]?.[0] || id;
export const iconOf = (id) =>
  id === 'pomegranate'
    ? '<svg class="pomegranate-icon" viewBox="0 0 40 40" aria-hidden="true"><defs><radialGradient id="pom"><stop stop-color="#da6c62"/><stop offset="1" stop-color="#9b2e36"/></radialGradient></defs><path d="m15 10-2-7 5 3 3-4 2 5 5-3-2 8" fill="#a94438"/><circle cx="20" cy="23" r="15" fill="url(#pom)"/><ellipse cx="16" cy="18" rx="6" ry="5" fill="#f4aa86" opacity=".28"/><path d="M24 12c12 7 10 20-1 23" fill="none" stroke="#842c35" stroke-width="2" opacity=".5"/></svg>'
    : ITEMS[id]?.[1] || '✦';
