export const SCENES = {
  intro: {
    label: 'PROLOGUE',
    title: 'A small red beginning',
    shots: [
      {
        x: -43,
        z: 83,
        y: 2,
        zoom: 17,
        angle: 0.7,
        text: 'In a pocket, a pomegranate.\nIn a heart, a very unreasonable dream.',
      },
      {
        x: -22,
        z: 29,
        y: 2,
        zoom: 26,
        angle: 0.85,
        text: 'Somewhere on this little island,\nthere was a place to call home.',
      },
      {
        x: 61,
        z: -82,
        y: 3,
        zoom: 14,
        angle: 0.4,
        text: 'No coins. No grand plan.\nJust one small trade at a time.',
      },
      {
        x: -30,
        z: 53,
        y: 2,
        zoom: 15,
        angle: 0.7,
        text: 'And so NarNar took a breath…\nand went to meet the neighbours.',
      },
    ],
  },
  first: {
    label: 'THE FIRST TRADE',
    title: 'One good thing becomes another',
    shots: [
      {
        x: -27,
        z: 47,
        y: 2,
        zoom: 9,
        angle: 0.3,
        text: '“A house?” Mara smiled.\n“Well, everyone starts somewhere.”',
      },
      {
        x: -26,
        z: 43,
        y: 3,
        zoom: 12,
        angle: 1.1,
        text: 'A pomegranate became a jar of jam.\nA stranger became a friend.',
      },
      {
        x: -20,
        z: 34,
        y: 2,
        zoom: 21,
        angle: 0.8,
        text: 'And a very unreasonable dream\nfelt a tiny bit more possible.',
      },
    ],
  },
  middle: {
    label: 'THE ISLAND REMEMBERS',
    title: 'Bring the light home',
    shots: [
      {
        x: -54,
        z: -76,
        y: 10,
        zoom: 14,
        angle: 0.4,
        text: 'Low. Middle. High.\nThe old song travelled over the sea.',
      },
      {
        x: -54,
        z: -76,
        y: 8,
        zoom: 23,
        angle: 1.2,
        text: 'For the first time in years,\nNorthlight opened its golden eye.',
      },
      {
        x: 0,
        z: 8,
        y: 3,
        zoom: 28,
        angle: 0.6,
        text: 'All across the island, neighbours looked up.\nSomeone had remembered the way home.',
      },
      {
        x: -49,
        z: -64,
        y: 2,
        zoom: 11,
        angle: 0.9,
        text: '“You came here to find a house,” Orin said.\n“Look what you have already made.”',
      },
    ],
  },
  end: {
    label: 'EPILOGUE',
    title: 'Enough, at last',
    shots: [
      {
        x: 60,
        z: -80,
        y: 3,
        zoom: 13,
        angle: 0.45,
        text: 'The key turned. The kettle sang.\nThe sea went on being the sea.',
      },
      {
        x: 64,
        z: -80,
        y: 2,
        zoom: 9,
        angle: 1,
        text: 'On the table: warm bread, a jar of jam,\nand a pomegranate from a friend.',
      },
      {
        x: 61,
        z: -82,
        y: 4,
        zoom: 19,
        angle: 0.8,
        text: 'Some trades make you richer.\nSome make you belong.',
      },
      {
        x: 60,
        z: -80,
        y: 4,
        zoom: 27,
        angle: 1.1,
        text: 'And the little penguin,\nat last, had nowhere else to be.',
      },
    ],
  },
};
